const programData = {
  Regular: {
    UG: {
      programs: [
        { id: "BAHISAD01", name: "B.A. History" },
        { id: "BAPOLAD01", name: "B.A. Political Science" },
        { id: "BAECOAD01", name: "B.A. Economics" },
        { id: "BAPHIAD01", name: "B.A. Philosophy" },
        { id: "BATAMAD01", name: "B.A. Tamil" },
        { id: "BAENGAD01", name: "B.A. English Language and Literature" },
        { id: "BCOMAD01", name: "B.Com" },
        { id: "BSCMAT01", name: "B.Sc. Mathematics" },
        { id: "BSCSTA01", name: "B.Sc. Statistics" },
        { id: "BSCPHY01", name: "B.Sc. Physics" },
        { id: "BSCCHE01", name: "B.Sc. Chemistry" },
        { id: "BSCBOT01", name: "B.Sc. Plant Biology and Plant Biotechnology" },
        { id: "BSCZOO01", name: "B.Sc. Zoology" },
      ],
      years: [1, 2, 3],
      semesters: {
        1: [1, 2],
        2: [3, 4],
        3: [5, 6],
      },
      batches: ["2023-2026", "2024-2027", "2025-2028"],
    },
    PG: {
      programs: [
        { id: "MAHISAD01", name: "M.A. History" },
        { id: "MAPOLAD01", name: "M.A. Political Science" },
        { id: "MAPUBAD01", name: "M.A. Public Administration" },
        { id: "MAECOAD01", name: "M.A. Economics" },
        { id: "MAPHIAD01", name: "M.A. Philosophy" },
        { id: "MATAMAD01", name: "M.A. Tamil" },
        { id: "MAENGAD01", name: "M.A. English Language and Literature" },
        { id: "MCOMAD01", name: "M.Com" },
        {
          id: "MSOCAD01",
          name: "M.S.W (Community Development / Medical and Psychiatry)",
        },
        { id: "MSCMAT01", name: "M.Sc. Mathematics" },
        { id: "MSCSTA01", name: "M.Sc. Statistics" },
        { id: "MSCPHY01", name: "M.Sc. Physics" },
        { id: "MSCCHE01", name: "M.Sc. Chemistry" },
        { id: "MSCBOT01", name: "M.Sc. Plant Biology and Plant Biotechnology" },
        { id: "MSCZOO01", name: "M.Sc. Zoology" },
      ],
      years: [1, 2],
      semesters: {
        1: [1, 2],
        2: [3, 4],
      },
      batches: ["2024-2026", "2025-2027"],
    },
  },

  "self-financed": {
    UG: {
      programs: [
        { id: "BAENGSF01", name: "B.A. English Language and Literature" },
        {
          id: "BAHISVOC01",
          name: "B.A. History – Voc (Archeology and Museology)",
        },
        { id: "BAJOURSF01", name: "B.A. Journalism" },
        { id: "BSWSF01", name: "B.S.W. Social Work" },
        { id: "BCOMSF01", name: "B.Com" },
        { id: "BCOMAFSF01", name: "B.Com Accounting and Finance" },
        { id: "BCOMPASF01", name: "B.Com Professional Accounting" },
        { id: "BBASF01", name: "B.B.A. Business Administration" },
        { id: "BCASF01", name: "B.C.A. Computer Application" },
        { id: "BSCMATSF01", name: "B.Sc. Mathematics" },
        { id: "BSCPHYSF01", name: "B.Sc. Physics" },
        { id: "BSCMICSF01", name: "B.Sc. Microbiology" },
        { id: "BSCVCSF01", name: "B.Sc. Visual Communication" },
        { id: "BSCPSF01", name: "B.Sc. Physical Education" },
        { id: "BSCGEOSF01", name: "B.Sc. Geography" },
        { id: "BSCTOURSF01", name: "B.Sc. Hospitality and Tourism" },
        { id: "BSCPSYSF01", name: "B.Sc. Psychology" },
        { id: "BSCCSSF01", name: "B.Sc. Computer Science" },
      ],
      years: [1, 2, 3],
      semesters: {
        1: [1, 2],
        2: [3, 4],
        3: [5, 6],
      },
      batches: ["2023-2026", "2024-2027", "2025-2028"],
    },
    PG: {
      programs: [
        { id: "MAHISSF01", name: "M.A. History" },
        { id: "MAPOLSF01", name: "M.A. Political Science" },
        { id: "MAPUBSF01", name: "M.A. Public Administration" },
        { id: "MAECOSF01", name: "M.A. Economics" },
        { id: "MAPHISF01", name: "M.A. Philosophy" },
        { id: "MATAMSF01", name: "M.A. Tamil" },
        { id: "MAENGSF01", name: "M.A. English Language and Literature" },
        { id: "MCOMSF01", name: "M.Com" },
        {
          id: "MSOCSF01",
          name: "M.S.W (Community Development / Medical and Psychiatry)",
        },
        { id: "MSCMATSF01", name: "M.Sc. Mathematics" },
        { id: "MSCSTASF01", name: "M.Sc. Statistics" },
        { id: "MSCPHYSF01", name: "M.Sc. Physics" },
        { id: "MSCCHESF01", name: "M.Sc. Chemistry" },
        {
          id: "MSCBOTSF01",
          name: "M.Sc. Plant Biology and Plant Biotechnology",
        },
        { id: "MSCZOOSF01", name: "M.Sc. Zoology" },
        { id: "MCASF01", name: "M.C.A Computer Applications" },
      ],
      years: [1, 2],
      semesters: {
        1: [1, 2],
        2: [3, 4],
      },
      batches: ["2024-2026", "2025-2027"],
    },
  },
};

export default programData;
